**Consider the below code to answer further questions:**
```python
import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)
```

**Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.**

In [1]:
import numpy as np

# Create a list of strings
list_ = ['1', '2', '3', '4', '5']

# Convert the list to a numpy array
array_list = np.array(object=list_)

# Print the data types of the variables
print("Data type of list_:", type(list_))  # Output: Data type of list_: <class 'list'>
print("Data type of array_list:", type(array_list))  # Output: Data type of array_list: <class 'numpy.ndarray'>


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


**Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.**

In [2]:
import numpy as np

# Create a list of strings
list_ = ['1', '2', '3', '4', '5']

# Convert the list to a numpy array
array_list = np.array(object=list_)

# Print the data type of each element in the list
print("Data types of elements in list_:")
for item in list_:
    print(f"Element: {item}, Data type: {type(item)}")

# Print the data type of each element in the numpy array
print("\nData types of elements in array_list:")
for item in array_list:
    print(f"Element: {item}, Data type: {type(item)}")


Data types of elements in list_:
Element: 1, Data type: <class 'str'>
Element: 2, Data type: <class 'str'>
Element: 3, Data type: <class 'str'>
Element: 4, Data type: <class 'str'>
Element: 5, Data type: <class 'str'>

Data types of elements in array_list:
Element: 1, Data type: <class 'numpy.str_'>
Element: 2, Data type: <class 'numpy.str_'>
Element: 3, Data type: <class 'numpy.str_'>
Element: 4, Data type: <class 'numpy.str_'>
Element: 5, Data type: <class 'numpy.str_'>


**Q3. Considering the following changes in the variable, array_list:**

`array_list = np.array(object = list_, dtype = int)`

**Will there be any difference in the data type of the elements present in both the variables, `list_` and `array_list`? If so then print the data types of each and every element present in both the variables, `list_` and `array_list`.**

In [3]:
import numpy as np

# Create a list of strings
list_ = ['1', '2', '3', '4', '5']

# Convert the list to a numpy array of integers
# These changes ensure that the elements in array_list are of integer data type.
array_list = np.array(object=list_, dtype=int)

# Print the data types of elements in the list
print("Data types of elements in list_:")
for item in list_:
    print(f"Element: {item}, Data type: {type(item)}")

# Print the data types of elements in the numpy array
print("\nData types of elements in array_list:")
for item in array_list:
    print(f"Element: {item}, Data type: {type(item)}")


Data types of elements in list_:
Element: 1, Data type: <class 'str'>
Element: 2, Data type: <class 'str'>
Element: 3, Data type: <class 'str'>
Element: 4, Data type: <class 'str'>
Element: 5, Data type: <class 'str'>

Data types of elements in array_list:
Element: 1, Data type: <class 'numpy.int32'>
Element: 2, Data type: <class 'numpy.int32'>
Element: 3, Data type: <class 'numpy.int32'>
Element: 4, Data type: <class 'numpy.int32'>
Element: 5, Data type: <class 'numpy.int32'>


The data type of elements in the `list_` remains same `str` type. But, data type of elements in `array_list` becomes `numpy.int32` inplace of `numpy.str_`. 

**Consider the below code to answer further questions:**
```python
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)
```

**Q4. Write a code to find the following characteristics of variable, num_array:**

- (i) shape

- (ii) size

In [6]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]

# Convert the list to a numpy array
num_array = np.array(object=num_list)
# print the list
print("Given List:")
print(num_array)

# (i) Calculate and print the shape of the array
shape = num_array.shape
print(f"The shape of num_array is: {shape}")

# (ii) Calculate and print the size of the array
size = num_array.size
print(f"The size of num_array is: {size}")

Given List:
[[1 2 3]
 [4 5 6]]
The shape of num_array is: (2, 3)
The size of num_array is: 6


**Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.**

`[Hint: The size of the array will be 9 and the shape will be (3,3).]`

In [7]:
import numpy as np

# Create a numpy array of zeros with shape (3, 3)
# This function creates a new array with the specified shape and fills it with zeros.
zero_array = np.zeros(shape=(3, 3))

# Print the created array
print("Zero Array:")
print(zero_array)

Zero Array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


**Q6. Create an identity matrix of shape (5,5) using numpy functions?**

`[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]`

In [8]:
import numpy as np

# Create an identity matrix of shape (5, 5)
# An identity matrix has ones along the main diagonal and zeros elsewhere.
identity_matrix = np.identity(5)

# Print the created identity matrix
print("Identity Matrix:")
print(identity_matrix)

Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
